# syntax=docker/dockerfile:1

FROM python:3.11-slim AS base

WORKDIR /app

COPY requirements/train.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --timeout 300 --retries 10 -r train.txt


FROM base AS training

COPY src/ ./src/
COPY configs/ ./configs/

ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "src/train.py"]
